/*
 * This file is generated by jOOQ.
 */
package co.markwilkins.mythology.database.tables.records;


import co.markwilkins.mythology.database.tables.CharacterRelationships;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharacterRelationshipsRecord extends TableRecordImpl<CharacterRelationshipsRecord> implements Record3<String, Integer, Integer> {

    private static final long serialVersionUID = -2016749302;

    /**
     * Setter for <code>myth.character_relationships.relationship</code>.
     */
    public void setRelationship(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>myth.character_relationships.relationship</code>.
     */
    public String getRelationship() {
        return (String) get(0);
    }

    /**
     * Setter for <code>myth.character_relationships.character_id</code>.
     */
    public void setCharacterId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>myth.character_relationships.character_id</code>.
     */
    public Integer getCharacterId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>myth.character_relationships.related_character_id</code>.
     */
    public void setRelatedCharacterId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>myth.character_relationships.related_character_id</code>.
     */
    public Integer getRelatedCharacterId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CharacterRelationships.CHARACTER_RELATIONSHIPS.RELATIONSHIP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CharacterRelationships.CHARACTER_RELATIONSHIPS.CHARACTER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CharacterRelationships.CHARACTER_RELATIONSHIPS.RELATED_CHARACTER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getRelationship();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCharacterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getRelatedCharacterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getRelationship();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCharacterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRelatedCharacterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterRelationshipsRecord value1(String value) {
        setRelationship(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterRelationshipsRecord value2(Integer value) {
        setCharacterId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterRelationshipsRecord value3(Integer value) {
        setRelatedCharacterId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharacterRelationshipsRecord values(String value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CharacterRelationshipsRecord
     */
    public CharacterRelationshipsRecord() {
        super(CharacterRelationships.CHARACTER_RELATIONSHIPS);
    }

    /**
     * Create a detached, initialised CharacterRelationshipsRecord
     */
    public CharacterRelationshipsRecord(String relationship, Integer characterId, Integer relatedCharacterId) {
        super(CharacterRelationships.CHARACTER_RELATIONSHIPS);

        set(0, relationship);
        set(1, characterId);
        set(2, relatedCharacterId);
    }
}
