/*
 * This file is generated by jOOQ.
 */
package co.markwilkins.mythology.database.tables.records;


import co.markwilkins.mythology.database.tables.Characters;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CharactersRecord extends UpdatableRecordImpl<CharactersRecord> implements Record4<Integer, String, Integer, Integer> {

    private static final long serialVersionUID = -793298681;

    /**
     * Setter for <code>myth.characters.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>myth.characters.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>myth.characters.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>myth.characters.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>myth.characters.race_id</code>.
     */
    public void setRaceId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>myth.characters.race_id</code>.
     */
    public Integer getRaceId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>myth.characters.home_location_id</code>.
     */
    public void setHomeLocationId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>myth.characters.home_location_id</code>.
     */
    public Integer getHomeLocationId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Characters.CHARACTERS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Characters.CHARACTERS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Characters.CHARACTERS.RACE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Characters.CHARACTERS.HOME_LOCATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getRaceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getHomeLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRaceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getHomeLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharactersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharactersRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharactersRecord value3(Integer value) {
        setRaceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharactersRecord value4(Integer value) {
        setHomeLocationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CharactersRecord values(Integer value1, String value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CharactersRecord
     */
    public CharactersRecord() {
        super(Characters.CHARACTERS);
    }

    /**
     * Create a detached, initialised CharactersRecord
     */
    public CharactersRecord(Integer id, String name, Integer raceId, Integer homeLocationId) {
        super(Characters.CHARACTERS);

        set(0, id);
        set(1, name);
        set(2, raceId);
        set(3, homeLocationId);
    }
}
