mythology-db:
    image: mysql:5.7.22
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'mythology'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'mark'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
