package co.markwilkins.mythology.Character;

import co.markwilkins.mythology.Location.Location;
import co.markwilkins.mythology.Location.LocationRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.Optional;

@RestController
public class CharacterController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CharacterRepository characterRepository;
    @Autowired
    private LocationRepository locationRepository;

    @RequestMapping(value="/characters", method = RequestMethod.GET, produces="application/json")
    @ResponseBody
    public ResponseEntity<Iterable> getAllCharacters(@RequestParam(value="page", defaultValue = "0", required = true) int page) {

        Iterable res = characterRepository.findAll(new PageRequest(page, 20));
        return new ResponseEntity<Iterable>(res, HttpStatus.OK);
    }

    @RequestMapping(value="/character", method = RequestMethod.GET, produces="application/json")
    @ResponseBody
    public ResponseEntity<Character> getCharacter(@RequestParam(value="name", required=true) String name) {

        Character res = characterRepository.findFirstByName(name);

        if (res == null) return new ResponseEntity<>(HttpStatus.NOT_FOUND);

        return new ResponseEntity<>(res, HttpStatus.OK);
    }

    @RequestMapping(value="/character", method = RequestMethod.POST, produces="application/json")
    @ResponseBody
    public ResponseEntity<?> addNewCharacter (@Valid @RequestBody CharacterRequestBody body) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        String name = body.getName();
        Optional<Location> location = locationRepository.findById(body.getHomeLocation());

        if (!location.isPresent()) {
            return new ResponseEntity("location does not exist", HttpStatus.NOT_FOUND);
        }

        Character character = new Character();
        character.setName(name);
        character.setHome(location.get());
        characterRepository.save(character);
        return new ResponseEntity(character, HttpStatus.CREATED);
    }

}