/*
 * This file is generated by jOOQ.
 */
package co.markwilkins.mythology.database.tables;


import co.markwilkins.mythology.database.Indexes;
import co.markwilkins.mythology.database.Keys;
import co.markwilkins.mythology.database.Myth;
import co.markwilkins.mythology.database.tables.records.RacesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Races extends TableImpl<RacesRecord> {

    private static final long serialVersionUID = -1277124759;

    /**
     * The reference instance of <code>myth.races</code>
     */
    public static final Races RACES = new Races();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RacesRecord> getRecordType() {
        return RacesRecord.class;
    }

    /**
     * The column <code>myth.races.id</code>.
     */
    public final TableField<RacesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>myth.races.name</code>.
     */
    public final TableField<RacesRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>myth.races.description</code>.
     */
    public final TableField<RacesRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>myth.races.origin_location_id</code>.
     */
    public final TableField<RacesRecord, Integer> ORIGIN_LOCATION_ID = createField("origin_location_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>myth.races</code> table reference
     */
    public Races() {
        this(DSL.name("races"), null);
    }

    /**
     * Create an aliased <code>myth.races</code> table reference
     */
    public Races(String alias) {
        this(DSL.name(alias), RACES);
    }

    /**
     * Create an aliased <code>myth.races</code> table reference
     */
    public Races(Name alias) {
        this(alias, RACES);
    }

    private Races(Name alias, Table<RacesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Races(Name alias, Table<RacesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Races(Table<O> child, ForeignKey<O, RacesRecord> key) {
        super(child, key, RACES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Myth.MYTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RACES_ORIGIN_LOCATION_ID, Indexes.RACES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RacesRecord> getPrimaryKey() {
        return Keys.KEY_RACES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RacesRecord>> getKeys() {
        return Arrays.<UniqueKey<RacesRecord>>asList(Keys.KEY_RACES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RacesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RacesRecord, ?>>asList(Keys.RACES_IBFK_1);
    }

    public Locations locations() {
        return new Locations(this, Keys.RACES_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Races as(String alias) {
        return new Races(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Races as(Name alias) {
        return new Races(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Races rename(String name) {
        return new Races(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Races rename(Name name) {
        return new Races(name, null);
    }
}
