/*
 * This file is generated by jOOQ.
 */
package co.markwilkins.mythology.database;


import co.markwilkins.mythology.database.tables.Categories;
import co.markwilkins.mythology.database.tables.CharacterRelationships;
import co.markwilkins.mythology.database.tables.Characters;
import co.markwilkins.mythology.database.tables.Items;
import co.markwilkins.mythology.database.tables.Locations;
import co.markwilkins.mythology.database.tables.Races;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Myth extends SchemaImpl {

    private static final long serialVersionUID = 592371989;

    /**
     * The reference instance of <code>myth</code>
     */
    public static final Myth MYTH = new Myth();

    /**
     * The table <code>myth.categories</code>.
     */
    public final Categories CATEGORIES = co.markwilkins.mythology.database.tables.Categories.CATEGORIES;

    /**
     * The table <code>myth.characters</code>.
     */
    public final Characters CHARACTERS = co.markwilkins.mythology.database.tables.Characters.CHARACTERS;

    /**
     * The table <code>myth.character_relationships</code>.
     */
    public final CharacterRelationships CHARACTER_RELATIONSHIPS = co.markwilkins.mythology.database.tables.CharacterRelationships.CHARACTER_RELATIONSHIPS;

    /**
     * The table <code>myth.items</code>.
     */
    public final Items ITEMS = co.markwilkins.mythology.database.tables.Items.ITEMS;

    /**
     * The table <code>myth.locations</code>.
     */
    public final Locations LOCATIONS = co.markwilkins.mythology.database.tables.Locations.LOCATIONS;

    /**
     * The table <code>myth.races</code>.
     */
    public final Races RACES = co.markwilkins.mythology.database.tables.Races.RACES;

    /**
     * No further instances allowed
     */
    private Myth() {
        super("myth", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Categories.CATEGORIES,
            Characters.CHARACTERS,
            CharacterRelationships.CHARACTER_RELATIONSHIPS,
            Items.ITEMS,
            Locations.LOCATIONS,
            Races.RACES);
    }
}
